# .github/workflows/deploy.yml
name: Build & Publish to S3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write   # OIDC to AWS
  contents: read

env:
  NODE_VERSION: "20"
  AWS_REGION: "ca-central-1"          # change if needed
  S3_BUCKET: "peakworkstudios.com"    # your bucket name
  BUILD_DIR: "dist"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      # upload all assets with long cache, but keep index.html short
      - name: Sync assets to S3
        run: |
          aws s3 sync $BUILD_DIR s3://$S3_BUCKET --delete \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable"
          aws s3 cp $BUILD_DIR/index.html s3://$S3_BUCKET/index.html \
            --cache-control "public, max-age=60"